### ISSUE TITLE
Incompatible with all=true?

### ISSUE THREAD

**Issue by silverlyra** [skovhus/css-modules-flow-types#14] opened 2018-04-13 20:52 UTC
First, thank you for this project – I was really excited to discover it. 😄

I added a set of `module.file_ext` declarations that included `.scss`, ran a Webpack build to generate the `.scss.flow` files – and was surprised to find that Flow tried to parse the actual SCSS sources:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/client/colors.scss:1:14

Unexpected token #

     1│ $background: #27282D;
     2│ $navBackground: #2F313A;
     3│ $navBackgroundActive: #4D5160;
     4│ $logo: #FF5714;
``` 

I thought maybe the problem was that my project uses `module.name_mapper`. I tried removing it, I tried adding a new one:

```
module.name_mapper.extension='scss' -> '\1.scss.flow'
```

No avail.

Then I tried removing `all=true` from `.flowconfig`, added a single exploratory `// @flow` comment to a `.js` file that imports `.scss` – and voila! It works. Mistyping a class name in that file becomes an error caught by Flow.

Are you aware of this? Do you have any workaround? This could very well be an issue to raise upstream, but I wanted to raise it here first.

I'm on flow-bin 0.69.0.

**Comment by skovhus** [comment] 2018-04-15 11:10
Thanks for reporting this. I haven’t experienced this issue. 

It seems module mapper needs to be used when using all=true. 

Did you try the setup mentioned in the README “Support for other file extensions”.

**Comment by trevorgithub** [comment] 2018-12-18 22:20
I'm also seeing the same problem when using all=true in .flowconfig.  Here's part of my .flowconfig:

[ignore]
;contains a bunch of non-relevant ignores

[include]

[libs]
flow-typed-custom

[lints]

[options]
all=true
; Extensions
module.file_ext=.js
module.file_ext=.jsx
module.file_ext=.json
module.file_ext=.css
module.file_ext=.scss
module.file_ext=.sass
module.file_ext=.scss.module

[strict]

**Comment by skovhus** [comment] 2019-05-27 20:39
I'm closing as I cannot reproduce, please re-open if this is still an issue.

**Closed as completed by skovhus** 2019-05-27 20:39 UTC
